name: Sync Lore from Google Sheets

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */12 * * *" # every 12 hours; adjust as you like

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Generate data.js from Sheet
        run: npm run build:data
        env:
          SHEET_CSV_URL: ${{ secrets.SHEET_CSV_URL }}
      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: sync data.js from Google Sheets"
            git push
          else
            echo "No changes."
          fi
